posts/urls.py
from django.urls import path
from .views import (PostsListView, CreatePost, UpdatePost,
                     PostDetail, DeletePost)
app_name = "posts"


urlpatterns = [
    path('', PostsListView.as_view(), name='posts_list'),
    path('create/', CreatePost.as_view(), name='create_post'),
    path('detail/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('<int:pk>/edit/', UpdatePost.as_view(), name='update_post'),
    path('<int:pk>/delete/', DeletePost.as_view(), name='delete_post'),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('cards/', include('cards.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('comps/', include('comps.urls')),
    path('posts/', include('posts.urls')),
    path('contact/', include('contact.urls'))
    
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
model = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(blank=True, null=True)
    author = models.ForeignKey(model, on_delete=models.PROTECT)
    edited_date = models.DateTimeField(null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk':self.pk})

    def update(self):
        return reverse('posts:update_post', kwargs={'pk':self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    comment = models.CharField(max_length=200)
    author = models.ForeignKey(model, on_delete=models.PROTECT)


    def __str__(self):
        return self.comment
    
    def get_absolute_url(self):
        return reverse("posts:posts_list")

posts/forms.py
from django import forms
from .models import Post, Comment

class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        feilds = '__all__'
        exclude = ('author','published_date', 'edited_date',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views import View
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
import datetime
from .forms import PostCreationForm, CommentForm
from .models import Post



class PostsListView(ListView):
    model = Post
    context_object_name = "posts_list"
    template_name = 'posts/posts_list.html'

class CreatePost(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreationForm
    success_url = reverse_lazy("posts:posts_list")
    template_name = "posts/create_post.html"
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class CommentGet(DetailView):
    model = Post
    template_name = "posts/post_detail.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context



class CommentPost(SingleObjectMixin, FormView):
    model = Post
    template_name = "posts/post_detail.html"
    form_class = CommentForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        self.object = self.get_object()
        ob = self.object
        return reverse("posts:post_detail", kwargs={'pk':ob.pk})



class PostDetail(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)

class UpdatePost(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = "posts/update_post.html"
    fields = ('title', 'body',)
    def form_valid(self, form):
        form.instance.edited_date = datetime.datetime.now()
        return super().form_valid(form)
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class DeletePost(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "posts/delete_post.html"
    success_url = reverse_lazy("posts:posts_list")
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

posts/templates/posts/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Create Post</title>
{% endblock title %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Post</button>
</form>
{% endblock content %}

posts/templates/posts/delete_post.html
{% extends 'base.html' %}

{% block title %}
    <title>Delete {{ post.title }}</title>
{% endblock title %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <h2>Are You Sure to delete "{{ post.title }}" ?</h2>
    <button type="submit">Delete</button>
    <a href="{{ post.get_absolute_url }}">Cancel</a>
</form>
{% endblock content %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>{{ post.title }}</title>
{% endblock title %}

{% block content %}
<ul>
    <a href="{{ post.update }}">Edit</a>
    <a href="{% url 'posts:delete_post' post.pk %}">Delete</a>
    {% if post.thumb %}
        <img src="{{ post.thumb.url }}" alt="NOT FOUND">
    {% endif %}
    <p>Title: <li>{{post.title}}</li></p>
    <p>Body: <li>{{post.body}}</li></p>
    <p>Published Date: <li>{{post.published_date}}</li></p>
    {% if post.edited_date %}
        <p>Edited Date: <li>{{post.edited_date}}</li></p>
    {% endif %}
    <p>Author: <li>{{post.author}}</li></p>
    <h3>Comments</h3>
    {% for comment in post.comment_set.all %}
        <li>{{comment}} &middot; {{comment.author}}</li>
    {% endfor %}
    <h3>Add Comment</h3>
    <form method="post">
        {% csrf_token %}
        {{ form |crispy }}
        <button type="submit">Save</button>
    </form>
</ul>
{% endblock content %}

posts/templates/posts/posts_list.html
{% extends 'base.html' %} {% block title %}
<title>Posts</title>
{% endblock title %} {% block content %}
<a href="{% url 'posts:create_post' %}" style="text-align: center"
  >Post Something</a
>
{% if posts_list %}
<ul>
  {% for post in posts_list %}
  <p>
    Title:
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
  </p>
  <p>
    Author:
    <li>{{ post.author }}</li>
  </p>
  <p>
    Published At:
    <li>{{ post.published_date }}</li>
  </p>
  {% if post.comment_set.all %} {% for comment in post.comment_set.all %}
  <ul>
    <li>{{comment}} &middot; {{comment.author}}</li>
  </ul>
  {% endfor %} {% endif %} {% endfor %}
</ul>
{% else %}
<p>No Posts For Now</p>
{% endif %} {% endblock content %}

posts/templates/posts/update_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>{{ post.title }}</title>
{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form | crispy}}
    <button type="submit">Update</button>
</form>

{% endblock content %}